import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {useNavigate, useParams} from "react-router";
import {Button, Chip, Spinner} from "@heroui/react";
import {ArrowLeft, Archive, Check} from "lucide-react";
import {useCompany} from "../components/AppShell";
import {api, apiErrorMessage} from "../lib/api";
import {date, money} from "../lib/format";
import type {PurchaseInvoice} from "../lib/types";

export function PurchaseInvoiceDetailPage() {
  const {company, can} = useCompany(); const {id} = useParams(); const navigate = useNavigate(); const client = useQueryClient();
  const invoice = useQuery({queryKey: ["purchase-invoice", company?.id, id], enabled: Boolean(company?.id && id && can("purchase_invoice.view")), queryFn: () => api<PurchaseInvoice>(`/companies/${company!.id}/purchase-invoices/${id}`)});
  const review = useMutation({mutationFn: () => api<PurchaseInvoice>(`/companies/${company!.id}/purchase-invoices/${id}/review`, {method: "PATCH", body: JSON.stringify({review_status: "reviewed"})}), onSuccess: () => {void client.invalidateQueries({queryKey: ["purchase-invoice", company?.id, id]}); void client.invalidateQueries({queryKey: ["purchase-invoices", company?.id]});}});
  if (!can("purchase_invoice.view")) return <p className="text-[var(--danger)]">Nu ai permisiunea necesară pentru facturile furnizorilor.</p>;
  if (invoice.isLoading) return <div className="flex justify-center py-24"><Spinner/></div>;
  if (!invoice.data) return <p className="text-[var(--danger)]">Factura nu a putut fi încărcată.</p>;
  const item = invoice.data.data;
  return <div className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onPress={() => navigate("/achizitii")}><ArrowLeft size={16}/> Înapoi</Button><div className="flex gap-2">{can("fiscal_vault.view") ? <Button variant="outline" onPress={() => navigate(`/seif-fiscal/${item.vault_item_id}`)}><Archive size={16}/> Vezi originalul în Seif</Button> : null}{!company?.archived_at && item.review_status !== "reviewed" && can("purchase_invoice.review") ? <Button variant="primary" isPending={review.isPending} onPress={() => review.mutate()}><Check size={16}/> Marchează verificată</Button> : null}</div></div>
    {review.isError ? <p role="alert" className="text-sm text-[var(--danger)]">{apiErrorMessage(review.error, "Factura nu a putut fi marcată drept verificată.")}</p> : null}
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow)]"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-sm text-[var(--text-muted)]">{item.document_type === "credit_note" ? "Notă de credit" : "Factură furnizor"}</p><h2 className="mt-1 text-2xl font-bold">{item.number}</h2><p className="mt-2 font-medium">{item.supplier?.name}</p><p className="text-sm text-[var(--text-muted)]">CUI {item.supplier?.tax_id ?? "—"}</p>{item.document_type === "credit_note" && item.referenced_invoice_number ? <div className="mt-2 flex items-center gap-1 text-sm"><span>Corectează factura</span>{item.corrects_purchase_invoice_id ? <Button size="sm" variant="ghost" onPress={() => navigate(`/achizitii/${item.corrects_purchase_invoice_id}`)}>{item.referenced_invoice_number}</Button> : <span className="font-semibold">{item.referenced_invoice_number}</span>}</div> : null}</div><div className="text-right"><div className="text-2xl font-bold">{money(item.total_cents, item.currency)}</div><p className="mt-2 text-sm">Emisă {date(item.issue_date)}</p><p className="text-sm">Scadentă {date(item.due_date)}</p><Chip className="mt-3" color={item.review_status === "reviewed" ? "success" : item.review_status === "needs_attention" ? "danger" : "warning"} variant="soft"><Chip.Label>{item.review_status === "reviewed" ? "Verificată" : item.review_status === "needs_attention" ? "Necesită atenție" : "De verificat"}</Chip.Label></Chip></div></div></section>
    <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full text-sm"><thead className="bg-[var(--bg-muted)] text-left"><tr><th className="p-3">Descriere</th><th className="p-3 text-right">Cantitate</th><th className="p-3 text-right">Valoare</th><th className="p-3 text-right">TVA</th></tr></thead><tbody>{item.lines.map((line) => <tr key={line.id} className="border-t border-[var(--border)]"><td className="p-3">{line.description}</td><td className="p-3 text-right tabular-nums">{line.quantity} {line.unit_code}</td><td className="p-3 text-right tabular-nums">{money(line.subtotal_cents, item.currency)}</td><td className="p-3 text-right tabular-nums">{line.vat_rate}%</td></tr>)}</tbody><tfoot><tr className="border-t border-[var(--border)] font-semibold"><td colSpan={2} className="p-3 text-right">TVA</td><td colSpan={2} className="p-3 text-right">{money(item.vat_cents, item.currency)}</td></tr><tr className="border-t border-[var(--border)] text-lg font-bold"><td colSpan={2} className="p-3 text-right">Total</td><td colSpan={2} className="p-3 text-right">{money(item.total_cents, item.currency)}</td></tr></tfoot></table></section>
  </div>;
}
