import {useEffect,useState} from "react";
import {NavLink,Outlet,useLocation,useNavigate} from "react-router";
import {useQuery} from "@tanstack/react-query";
import {Bell,ChevronDown,CircleGauge,CreditCard,FileClock,FileText,LogOut,Menu,Moon,Plus,ReceiptText,Search,Settings,Sun,Users,X} from "lucide-react";
import {api,session} from "../lib/api";
import type {Company,User} from "../lib/types";
const items=[{to:"/dashboard",label:"Dashboard",icon:CircleGauge,group:"Principal"},{to:"/facturi",label:"Facturi",icon:FileText,group:"Principal"},{to:"/recurente",label:"Facturi recurente",icon:FileClock,group:"Principal"},{to:"/clienti",label:"Clienți",icon:Users,group:"Date firmă"},{to:"/conturi",label:"Conturi bancare",icon:CreditCard,group:"Date firmă"},{to:"/serii",label:"Serii de facturare",icon:ReceiptText,group:"Date firmă"},{to:"/setari",label:"Setări",icon:Settings,group:"Date firmă"}];
const meta:Record<string,[string,string]>={"/dashboard":["Dashboard","Sumarul activității firmei tale"],"/facturi":["Facturi","Toate documentele emise"],"/recurente":["Facturi recurente","Automatizări active"],"/clienti":["Clienți","Firmele cu care lucrezi"],"/conturi":["Conturi bancare","Conturile afișate pe facturi"],"/serii":["Serii de facturare","Prefixe și numerotare"],"/setari":["Setări","Date firmă și preferințe"]};
export function AppShell(){const[open,setOpen]=useState(false);const[dark,setDark]=useState(()=>localStorage.getItem("billwise_theme")==="dark");const navigate=useNavigate();const location=useLocation();const me=useQuery({queryKey:["me"],queryFn:()=>api<User>("/me")});const companies=useQuery({queryKey:["companies"],queryFn:()=>api<Company[]>("/companies")});const company=companies.data?.data?.[0];const[title,subtitle]=meta[location.pathname]??["BillWise","Administrare firmă"];
useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("billwise_theme",dark?"dark":"light")},[dark]);
const logout=async()=>{try{await api("/auth/logout",{method:"POST"})}finally{session.clear();navigate("/login",{replace:true})}};
return <div className="app-frame">{open&&<button className="sidebar-backdrop" aria-label="Închide meniul" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?"is-open":""}`}><div className="brand"><span className="brand-mark">B</span><span>BillWise</span><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div><button className="company-switcher"><span className="company-avatar">{company?.name?.slice(0,2).toUpperCase()??"BW"}</span><span><b>{company?.name??"Firma ta"}</b><small>{company?.tax_identifier??company?.cui??"Selectează compania"}</small></span><ChevronDown size={15}/></button><button className="primary-action" onClick={()=>navigate("/facturi/noi")}><Plus size={17}/>Emite factură</button>{["Principal","Date firmă"].map(group=><nav key={group} className="nav-group"><p>{group}</p>{items.filter(i=>i.group===group).map(({to,label,icon:Icon})=><NavLink key={to} to={to} onClick={()=>setOpen(false)}><Icon size={18}/><span>{label}</span></NavLink>)}</nav>)}<div className="user-card"><span className="user-avatar">{me.data?.data?.name?.split(" ").map(p=>p[0]).slice(0,2).join("")??"BW"}</span><span><b>{me.data?.data?.name??"Cont BillWise"}</b><small>{company?.name??me.data?.data?.email}</small></span><button aria-label="Deconectare" onClick={logout}><LogOut size={17}/></button></div></aside><div className="content-column"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setOpen(true)}><Menu size={19}/></button><div className="page-heading"><b>{title}</b><small>{subtitle}</small></div><div className="topbar-spacer"/><label className="global-search"><Search size={16}/><input placeholder="Caută facturi, clienți…"/></label><span className="status-pill success"><i/>SPV conectat</span><button className="icon-button" aria-label="Schimbă tema" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button notification" aria-label="Notificări"><Bell size={18}/><i/></button></header><main className="page-content"><Outlet context={{company}}/></main></div></div>}
