import {StrictMode} from "react";
import {createRoot} from "react-dom/client";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {createBrowserRouter, RouterProvider} from "react-router";
import {App} from "./app/App";
import {SessionProvider} from "./components/SessionProvider";
import "./styles.css";
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:30000,retry:1}}});
const router=createBrowserRouter([{path:"*",element:<SessionProvider><App/></SessionProvider>}]);
createRoot(document.getElementById("root")!).render(<StrictMode><QueryClientProvider client={queryClient}><RouterProvider router={router}/></QueryClientProvider></StrictMode>);
